export const orders = [
  {
    id: 1,
    serviceType: 'Laundary',
    email: 'ifenna@gmail.com',
    name: 'Ifenna Monanu',
    address: '11 Agege street',
    status: 'pending',
  },
  {
    id: 2,
    serviceType: 'Laundary',
    email: 'ifenna@gmail.com',
    name: 'Ifenna Monanu',
    address: '11 Agege street',
    status: 'processing',
  },
  {
    id: 3,
    serviceType: 'Laundary',
    email: 'ifenna@gmail.com',
    name: 'Ifenna Monanu',
    address: '11 Agege street',
    status: 'confirmed',
  },
  {
    id: 4,
    serviceType: 'Laundary',
    email: 'ifenna@gmail.com',
    name: 'Ifenna Monanu',
    address: '11 Agege street',
    status: 'completed',
  },
  {
    id: 5,
    serviceType: 'Laundary',
    email: 'ifenna@gmail.com',
    name: 'Ifenna Monanu',
    address: '11 Agege street',
    status: 'pending',
  },
  {
    id: 6,
    serviceType: 'Laundary',
    email: 'ifenna@gmail.com',
    name: 'Ifenna Monanu',
    address: '11 Agege street',
    status: 'confirmed',
  },
  {
    id: 7,
    serviceType: 'Laundary',
    email: 'ifenna@gmail.com',
    name: 'Ifenna Monanu',
    address: '11 Agege street',
    status: 'completed',
  },
];
