import Head from 'next/head'
import Hero from '../layout/hero/Hero'
import WhyChooseUs from '../section/home/WhyChooseUs'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Crystal Home Deterget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Hero />
     <WhyChooseUs />
    </div>
  )
}
